---
title: "SpideR To Do"
output:
  html_notebook:
    code_folding: none
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
    toc_float: yes
---

NOTE: No tasks were transferred from SpiderDev.Rmd. This should gradually be done in the future.
In the meantime, please also refer to SpiderDev.Rmd.  

### Legend

|Status|Meaning|
|-|-|
|+|Done|
|...|In progress|
|!!!|To be done!|



### Package setup


----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
  +    Download and attach packages

 ...   Connect to bioconductor packages (need to double check whether it works!)

  +    Explicitly call package functions, i.e. package::function(); check if this is a common practice or not --> Hadley

  +    Decide on the location of the sqlite files

  +    Decide on the acceptable age of all the files (include SRA, GEO and  SRR_GSM)

  +    Decide on the way of enforcing file age (stop vs offer the chance to update)

  +    Choose a method for establishing connections

  +    Display the current limit for database file age
----------------------------------------------------------------------------------------------------------------------




### Naming

----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 ...   Rename internal functions and update namespace file (gradually exporting functions)

 ...   Introduce consistent grammatical form and spelling for function names

 !!!   Introduce consistent naming of function variables
 
 !!!   Double check whether there are no traces of changed functions (e.g. accessionConverter vs convertAccession)
 
 !!!   Decide on the naming of reproduceResults
----------------------------------------------------------------------------------------------------------------------


### Function-specific tasks



----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 +      Get rid of the error of no results when no SRA/GEO correspondence...  
 
 ...    Manage the NA types  
----------------------------------------------------------------------------------------------------------------------

: Accession_Conversion


----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 !!!   Get rid of the error of no results when no SRA/GEO correspondence...

 !!!   Verify arguments

 !!!   Save query info and record

 !!!   Extract GSMs

 !!!   Extract sample_attribute and characteristics (create separate functions for that)

 !!!   Decide what to do about the format of the output for mixed library_strategy accessions

 !!!   Decide on what accessions to use by default - SRA or GEO?

----------------------------------------------------------------------------------------------------------------------

: searchForAccession


----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 !!!   Make sure that the file extension corresponds to separator

 !!!   Change function name to generateOutputs
----------------------------------------------------------------------------------------------------------------------

: outputGenerator


----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 !!!   Research properly different attributes

 !!!   Decide if it would be worthwhile to extract experiment_attributes
----------------------------------------------------------------------------------------------------------------------

: chExtractor

----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 !!!   Make digitSort output an ordered vector rather than vector of indices (double check that)

 !!!   Make digitSort more generalised (able to sort other strings (???)). Think about underscores etc.

 !!!   Make digitSort able to deal with NAs (in any form) !!!
----------------------------------------------------------------------------------------------------------------------

: digitSort (orderAccession/sortAccession!!!)


----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 !!!   Check whether behaviour is actually desirable

 !!!   Review function name
----------------------------------------------------------------------------------------------------------------------

: naConverter

### Search functionalities


----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 ...   Search for term

 !!!   Search by date (currently not possible - SRA does not list dates and the only available update_date is not in date format)
 
 !!!   Search by pubmed ids
 
 !!!   Search by bioproject ids
 
 !!!   Search by platform accesion
 
 !!!   Search by number of samples within the study
 
 !!!   Search by author
----------------------------------------------------------------------------------------------------------------------

: search functionalities



### General behaviour

----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 !!!   Consider how to communicate information to the users (warnings, print, message...)

 !!!   Consider what to do if entry only exists in GEO - input/control labelling, dealing with outputs 

 !!!   Sort out what happens with regard to the weird data types at the output (?)
 
 !!!   Check consistence of database handling: DBI::dbGetQuery(get(database_name, envir=get(database_envir)), query)
 
 !!!   Replace creation of global environment variables with a spider.env which will contain all the connections
----------------------------------------------------------------------------------------------------------------------



### Performance

----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 !!!   Investigate possibilities of more optimised queries
----------------------------------------------------------------------------------------------------------------------



### Testing

-----------------------------------------------------------------------------------------------------------------------
Status          Function            Task
------ -------------------------- --------------------------------------------------------------------------------------
 !!!         inputDetector            Prepare extracts for testing (with too few columns, crucial columns only, with some columns and all columns)

 !!!        controlDetector           As above

 !!!            digitSort             Test on simple examples

 !!!          columnVerifier          Much depends on it!!!

 ...        universalExtractor        Design tests for most problematic cases...

 ...   Accession_Search_Functions     Design tests for other functions

-----------------------------------------------------------------------------------------------------------------------

#### Accession_Search_Functions

----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
  +     Incorrect accessions

  +     Non-existent accessions

  +     Accessions of different types
  
  +     Wrong column names

  +     Correct number of matches
  
 !!!    More tests for correct matches
----------------------------------------------------------------------------------------------------------------------

: searchSRAForAccession

  
  
### Documentation



----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
  !!!     Package-level help - include basic usage examples and abstract style summary and links to further info (vignettes)

  !!!     Create a demo database from SRA and GEO for the vignette

----------------------------------------------------------------------------------------------------------------------

: Documentation

  
----------------------------------------------------------------------------------------  


----------------------------------------------------------------------------------------  
  
  

### Some experiences with tables

#### Basic tables

| Right-aligned | Left-aligned | Centered | Default |
|-:|:-|:-:|-|
|1|1|1|1|
|12|12|12|12| 
|*1*|_2_|~~3~~|4^2^|


|Status|Task|
|-|-----------|
|IP|Managing the output|

|Status|Task|
|-|-----------|
|IP|IP|

|Status|Task|
|-|-|
|IP|IP|



#### multiline_tables

Part of Pandoc Markdown 
(http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html#pandoc_markdown)  
Are suppressed by using markdown_strict as opposed to markdown.

-------------------------------------------------------------
 Centered   Default           Right Left
  Header    Aligned         Aligned Aligned
----------- ------- --------------- -------------------------
   First    row                12.0 Example of a row that
                                    spans multiple lines.

  Second    row                 5.0 Here's another one. Note
                                    the blank line between
                                    rows.
-------------------------------------------------------------

Table: This is the example from the website.




---------------------------------------------------------------------------------------------
 Head  Text
------ --------------------------------------------------------------------------------------
 !!!   Something multiline
       More?

 ...   Nothing
---------------------------------------------------------------------------------------------

: Almost successful multiline (new line is not recognised)




--------------------------------------------------------------------------------------------------------------------
Status Task
------ -------------------------------------------------------------------------------------------------------------
 ...   Download and attach packages

 !!!   Connect to bioconductor packages

 !!!   Explicitly call package functions, i.e. package::function(); check if this is a common practice or not --> Hadley

 !!!   Decide on the location of the sqlite files

 !!!   Choose a method for establishing connections
----------------------------------------------------------------------------------------------------------------------

: Fairly successful multiline (line is wrapped)




----------------------------------------------------------------------------------------------------------------------
Status Task
------ ---------------------------------------------------------------------------------------------------------------
 !!!   Sample task
----------------------------------------------------------------------------------------------------------------------

: This is a template of a table


#### Tasks

- [ ] Incomplete item
- [x] Supposedly complete item
Does not seem to work in R (github task lists)



