

#' Find Pubmed IDs based on GSE
#' 
#' @param df Data frame with series_id column containing GSEs
#' @return Data frame with appended pubmed_id column
#' 
#' NOTE: currently relies entirely on pubmed_id column in gse table from the database generated by GEOmetadb
#' It appears that only approximately 20% of entries in that column are in agreement with the online version of GEO (the rest has missing pubmed_ids)
#' 
#' @examples
#' findPubmedIDs(df)
#' 
#' @keywords internal
#' 
findPubmedIDs <- function(df){
  
  print("Running findPubmedIDs")
  
  database_name <- "geo_con"
  database_env <- ".GlobalEnv"
  
  if (sum(!is.na(df$series_id))==0){
    df$pubmed_id <- NA
    warning("No GSEs to use for searching for pubmed_id")
    print("findPubmedIDs completed")
    return(df)
  }
  
  #Insert clause about no entries ===*===
  
  df_length <- dim(df)[1]
  df$pubmed_id <- NA
  for (i in 1:df_length){
    series <- df$series_id[i]
    series <- unlist(strsplit(series, split = ","))
    p <- NULL
    for (j in seq_along(series)){
      p <- c(p, as.character(DBI::dbGetQuery(get(database_name, envir = get(database_env)), paste0("SELECT pubmed_id FROM gse WHERE gse = '", series[j], "'"))))
    }
    #p <- c("NA", "NA", 8, 9, NA,11)
    p <- unique(p)
    
    p[grepl("^NA$", p)] <- NA #Replace character NAs with real NAs
    
    if (length(p) >1){
      p <- p[!is.na(p)]
    }
    p <- paste(p, collapse = ",")
    df$pubmed_id[i] <- p
  }
  
  #df <- df[,c(1:5, 33, 6:32)]
  
  print("findPubmedIDs completed")
  return(df)
  
  
}




#ss_sample <- dbGetQuery(geo_con, "SELECT * FROM gsm WHERE series_id LIKE '%,%' ORDER BY RANDOM() LIMIT 50")
saveRDS(ss_sample, "ss_sample_gsm_with_multiple_gses.Rda")

test1 <- gsm_sample[1:3,]
test1 <- gsm_sample[1:6,]
test1 <- gsm_sample[7:13,]
x <- test1
x <- ss_sample

database_name <- "geo_con"
database_env <- ".GlobalEnv"


x_length <- dim(x)[1]
x$pubmed_id <- NA
for (i in 1:x_length){
  series <- x$series_id[i]
  series <- unlist(strsplit(series, split = ","))
  p <- NULL
  for (j in seq_along(series)){
    p <- c(p, as.character(DBI::dbGetQuery(get(database_name, envir = get(database_env)), paste0("SELECT pubmed_id FROM gse WHERE gse = '", series[j], "'"))))
  }
  #p <- c("NA", "NA", 8, 9, NA,11)
  p <- unique(p)
  
  p[grepl("^NA$", p)] <- NA #Replace character NAs with real NAs
  
  if (length(p) >1){
    p <- p[!is.na(p)]
  }
  p <- paste(p, collapse = ",")
  x$pubmed_id[i] <- p
}
x <- x[,c(1:5, 33, 6:32)]


#------------------------------


p <- c(1,2,"NA",4)
k <- as.character(c(1:3,NA,5:8,NA,10))
k <- as.character(c(1:3,"NA",5:8,"NA",10))

ind <- !grepl("^NA$", p)
p[ind]
p[p!="NA"] #Don't work


